version: '3.8'

services:
  platform-db:
    image: mysql:8.0
    container_name: dashmint_platform_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: platform_root
      MYSQL_DATABASE: dashmint_platform
    ports:
      - "3308:3306"
    volumes:
      - platform_db_data:/var/lib/mysql

  customer-db:
    image: mysql:8.0
    container_name: dashmint_customer_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: customer_root
      MYSQL_DATABASE: dashmint_customer
    ports:
      - "3307:3306"
    volumes:
      - customer_db_data:/var/lib/mysql
      - ./scripts/init_customer_db.sql:/docker-entrypoint-initdb.d/init_customer_db.sql

volumes:
  platform_db_data:
  customer_db_data:
