version: '3.8'

services:
  platform-db:
    image: mysql:8.0
    container_name: dashmint_platform_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: platform_root
      MYSQL_DATABASE: dashmint_platform
    ports:
      - "3308:3306"
    volumes:
      - platform_db_data:/var/lib/mysql
volumes:
  platform_db_data:
